version: "3.9"
services:
  database:
    image: postgres
    restart: always
    environment: 
      POSTGRES_PASSWORD: keyboardcat
    ports:
    - "5432:5432"
    volumes:
    - ./init.sql:/docker-entrypoint-initdb.d/init.sql
  wait_for_it:
    image: toschneck/wait-for-it
    command: database:5432
  hasura:
    image: hasura/graphql-engine
    ports:
    - "8080:8080"
    depends_on:
    - "wait_for_it"
    restart: always
    environment: 
      HASURA_GRAPHQL_DATABASE_URL: postgres://postgres:keyboardcat@database:5432/postgres
      HASURA_GRAPHQL_ENABLE_CONSOLE: "true"
      HASURA_GRAPHQL_ADMIN_SECRET: keyboardcat